first commit module7-task1 19.4.22
htmlacademy-vue/1946779-pizza-1 pull request #7
Opened 2022-04-19 07:27 UTC by EduardoAlparov

2022-04-19 09:40 UTC, rvladimir001 commented
Требуется дополнить тестами компоненты AppDrag.vue, AppDrop.vue, store и т.д. Рекомендую посмотреть процент покрытия по компонентам и обратить внимание на компоненты с низкими значения покрытия (команда: npx jest --coverage). Так же нужно обратить внимание на неиспользуемые импорты (ниже несколько для примера).

2022-04-19 09:41 UTC, rvladimir001 commented on src/frontend/src/common/__test__/helpers.spec.js
> +import { dough_types, pizza_sizes, pizza_sauces, pizza_ingredients, misc_types  } from '@/common/constants';
не используемый импорт

2022-04-19 09:43 UTC, rvladimir001 commented on src/frontend/src/common/components/__tests__/AppInput.spec.js
> +import { shallowMount, mount } from '@vue/test-utils';
неиспользуемый импорт mount

2022-04-19 09:45 UTC, rvladimir001 commented on src/frontend/src/modules/builder/__test__/BuilderDoughSelector.spec.js
> +import pizza from '@/static/pizza';
неиспользуемые импорты pizza, normalizeSauce и тд

2022-04-24 11:34 UTC, Djaler commented on src/frontend/src/common/components/__tests__/AppDrag.spec.js
> +    await wrapper.find('[data-test="drag-div"]').trigger('dragstart', dataTransfer());
тут не хватает проверки, собственно. dataTransfer.setData можно сделать моком (jest.fn) и вот тут потом проверить, что он был вызван с ожидаемыми данными

2022-04-24 11:53 UTC, Djaler commented on src/frontend/src/modules/builder/__test__/BuilderDoughSelector.spec.js
> +    const spyOnMutation = jest.spyOn(wrapper.vm, 'addDough');
вот это в целом не очень хорошая практика. потому что, например, ты перестанешь пользоваться mapMutations, компонент будет работать точно так же, а тест упадёт. Потому что тест сильно влазит в детали реализации - то, что дергается какой-то метод компонента.
Тут несколько вариантов:
1) Дергать из компонента не мутацию, а экшен. Тогда этот экшен можно замокать и проверять вызов этого мока
2) Проверять не сам факт вызова мутации, а то, что состояние изменилось соответствующим образом. Но это уже чуть более интеграционный тест, так как мы заодно проверяем и правильность кода мутации

2022-04-24 12:26 UTC, Djaler commented on src/frontend/src/modules/order/__test__/OrderAdditionalItem.spec.js
> +    expect(miscImg.attributes('alt')).toBe(miscs.find( el => orders[0].orderMisc[0].miscId === el.id)?.name);
вот тут по сути в тесте дублируется логика из компонента.
Хорошо бы ожидаемое значение явно прописать, хардкодом

2022-04-24 12:27 UTC, Djaler requested changes
В общем, такие вот небольшие замечания, но ничего критичного.

2022-04-24 17:54 UTC, merged